"""initial schema for jdr service

Revision ID: 25a849ed7115
Revises: 
Create Date: 2026-05-05 13:31:00.141841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a849ed7115'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jdr_api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('GM', 'PLAYER', name='jdr_role'), nullable=False),
    sa.Column('pj_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='jdr_api_key_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pj_id'], ['jdr_pjs.id'], name='fk_jdr_api_keys_pj_id_jdr_pjs', ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jdr_api_keys')),
    sa.UniqueConstraint('name', name=op.f('uq_jdr_api_keys_name'))
    )
    op.create_table('jdr_pjs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_gm_key_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_gm_key_id'], ['jdr_api_keys.id'], name=op.f('fk_jdr_pjs_owner_gm_key_id_jdr_api_keys'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jdr_pjs')),
    sa.UniqueConstraint('owner_gm_key_id', 'name', name='owner_name')
    )
    op.create_index(op.f('ix_jdr_pjs_owner_gm_key_id'), 'jdr_pjs', ['owner_gm_key_id'], unique=False)
    op.create_table('jdr_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gm_key_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('BATCH', 'LIVE', name='jdr_session_mode'), nullable=False),
    sa.Column('state', sa.Enum('CREATED', 'AUDIO_UPLOADED', 'TRANSCRIBING', 'TRANSCRIPTION_FAILED', 'TRANSCRIBED', name='jdr_session_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gm_key_id'], ['jdr_api_keys.id'], name=op.f('fk_jdr_sessions_gm_key_id_jdr_api_keys'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jdr_sessions'))
    )
    op.create_index(op.f('ix_jdr_sessions_gm_key_id'), 'jdr_sessions', ['gm_key_id'], unique=False)
    op.create_table('jdr_artifacts',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['jdr_sessions.id'], name=op.f('fk_jdr_artifacts_session_id_jdr_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'kind', name=op.f('pk_jdr_artifacts'))
    )
    op.create_table('jdr_audio_sources',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['jdr_sessions.id'], name=op.f('fk_jdr_audio_sources_session_id_jdr_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_jdr_audio_sources'))
    )
    op.create_table('jdr_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('TRANSCRIPTION', 'NARRATIVE', 'ELEMENTS', 'POVS', name='jdr_job_kind'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='jdr_job_status'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['jdr_sessions.id'], name=op.f('fk_jdr_jobs_session_id_jdr_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jdr_jobs'))
    )
    op.create_index(op.f('ix_jdr_jobs_session_id'), 'jdr_jobs', ['session_id'], unique=False)
    op.create_table('jdr_session_pj_mappings',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('speaker_label', sa.String(length=64), nullable=False),
    sa.Column('pj_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pj_id'], ['jdr_pjs.id'], name=op.f('fk_jdr_session_pj_mappings_pj_id_jdr_pjs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['jdr_sessions.id'], name=op.f('fk_jdr_session_pj_mappings_session_id_jdr_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'speaker_label', name=op.f('pk_jdr_session_pj_mappings'))
    )
    op.create_index(op.f('ix_jdr_session_pj_mappings_pj_id'), 'jdr_session_pj_mappings', ['pj_id'], unique=False)
    op.create_table('jdr_transcriptions',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('segments_json', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('model_used', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['jdr_sessions.id'], name=op.f('fk_jdr_transcriptions_session_id_jdr_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_jdr_transcriptions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jdr_transcriptions')
    op.drop_index(op.f('ix_jdr_session_pj_mappings_pj_id'), table_name='jdr_session_pj_mappings')
    op.drop_table('jdr_session_pj_mappings')
    op.drop_index(op.f('ix_jdr_jobs_session_id'), table_name='jdr_jobs')
    op.drop_table('jdr_jobs')
    op.drop_table('jdr_audio_sources')
    op.drop_table('jdr_artifacts')
    op.drop_index(op.f('ix_jdr_sessions_gm_key_id'), table_name='jdr_sessions')
    op.drop_table('jdr_sessions')
    op.drop_index(op.f('ix_jdr_pjs_owner_gm_key_id'), table_name='jdr_pjs')
    op.drop_table('jdr_pjs')
    op.drop_table('jdr_api_keys')
    # ### end Alembic commands ###
